# Generated by Django 6.1.1 on 2026-09-15 18:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Áreas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='gestion.area')),
            ],
            options={
                'verbose_name_plural': 'Cargos',
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'area')},
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('PA', 'Pasaporte'), ('NIT', 'NIT')], default='CC', max_length=20)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(default=datetime.date.today)),
                ('salario_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='gestion.area')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='gestion.cargo')),
                ('jefe', models.ForeignKey(blank=True, help_text='Jefe inmediato. Define la jerarquía del organigrama.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='gestion.empleado')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Empleados',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Dotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('UNIFORME', 'Uniforme'), ('EPP', 'Elemento de protección (EPP)'), ('HERRAMIENTA', 'Herramienta'), ('OTRO', 'Otro')], max_length=15)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_entrega', models.DateField(default=datetime.date.today)),
                ('fecha_cambio', models.DateField(blank=True, help_text='Fecha programada para reposición/cambio.', null=True)),
                ('estado', models.CharField(choices=[('ENTREGADA', 'Entregada'), ('PENDIENTE', 'Pendiente'), ('DEVUELTA', 'Devuelta')], default='ENTREGADA', max_length=12)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dotaciones', to='gestion.empleado')),
            ],
            options={
                'verbose_name_plural': 'Dotaciones',
                'ordering': ['-fecha_entrega'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INDEFINIDO', 'Término indefinido'), ('FIJO', 'Término fijo'), ('OBRA_LABOR', 'Obra o labor'), ('PRESTACION_SERVICIOS', 'Prestación de servicios'), ('APRENDIZAJE', 'Contrato de aprendizaje')], max_length=25)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, help_text='Obligatoria para término fijo, obra/labor y aprendizaje.', null=True)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('modalidad', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('REMOTO', 'Remoto'), ('HIBRIDO', 'Híbrido')], default='PRESENCIAL', max_length=15)),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('FINALIZADO', 'Finalizado')], default='VIGENTE', max_length=12)),
                ('observaciones', models.TextField(blank=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='gestion.empleado')),
            ],
            options={
                'verbose_name_plural': 'Contratos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='NominaPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Periodos de nómina',
                'ordering': ['-anio', '-mes'],
                'unique_together': {('anio', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='NovedadNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(choices=[('HORAS_EXTRA', 'Horas extra'), ('RECARGO_NOCTURNO', 'Recargo nocturno'), ('DOMINICAL_FESTIVO', 'Trabajo dominical/festivo'), ('BONIFICACION', 'Bonificación'), ('COMISION', 'Comisión'), ('INCAPACIDAD', 'Incapacidad'), ('AUSENCIA', 'Ausencia no justificada'), ('DESCUENTO', 'Descuento autorizado'), ('EMBARGO', 'Embargo'), ('OTRO_DEVENGADO', 'Otro devengado'), ('OTRO_DEDUCIDO', 'Otra deducción')], max_length=25)),
                ('movimiento', models.CharField(choices=[('DEVENGADO', 'Devengado (suma)'), ('DEDUCIDO', 'Deducido (resta)')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, help_text='Cantidad: horas, días o unidades.', max_digits=8)),
                ('valor_unitario', models.DecimalField(decimal_places=2, help_text='Valor por unidad. El total = cantidad × valor unitario.', max_digits=12)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='gestion.empleado')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='gestion.nominaperiodo')),
            ],
            options={
                'verbose_name_plural': 'Novedades de nómina',
                'ordering': ['empleado', 'concepto'],
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VACACIONES', 'Vacaciones'), ('LICENCIA_REMUNERADA', 'Licencia remunerada'), ('LICENCIA_NO_REMUNERADA', 'Licencia no remunerada'), ('PERMISO_REMUNERADO', 'Permiso remunerado'), ('PERMISO_NO_REMUNERADO', 'Permiso no remunerado'), ('INCAPACIDAD', 'Incapacidad')], max_length=25)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('motivo', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='gestion.empleado')),
            ],
            options={
                'verbose_name_plural': 'Permisos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('salario_ofrecido', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha_apertura', models.DateField(default=datetime.date.today)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=10)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacantes', to='gestion.cargo')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacantes_responsables', to='gestion.empleado')),
            ],
            options={
                'verbose_name_plural': 'Vacantes',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('fuente', models.CharField(blank=True, help_text='LinkedIn, computrabajo, referido…', max_length=50)),
                ('etapa', models.CharField(choices=[('POSTULADO', 'Postulado'), ('SCREENING', 'Filtrado (screening)'), ('ENTREVISTA', 'Entrevista'), ('PRUEBA', 'Prueba técnica'), ('OFERTA', 'Oferta'), ('CONTRATADO', 'Contratado'), ('RECHAZADO', 'Rechazado')], default='POSTULADO', max_length=15)),
                ('notas', models.TextField(blank=True)),
                ('fecha_postulacion', models.DateField(default=datetime.date.today)),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='gestion.vacante')),
            ],
            options={
                'verbose_name_plural': 'Candidatos',
                'ordering': ['vacante', '-fecha_postulacion'],
            },
        ),
    ]
