# Generated by Django 6.1.1 on 2026-09-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_candidato_fecha_postulacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalarioMinimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(unique=True, verbose_name='Año')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Salario mínimo (SMMLV)',
                'verbose_name_plural': 'Salarios mínimos (SMMLV)',
                'ordering': ['-anio'],
            },
        ),
        migrations.RemoveField(
            model_name='dotacion',
            name='fecha_cambio',
        ),
        migrations.RemoveField(
            model_name='dotacion',
            name='tipo',
        ),
        migrations.AddField(
            model_name='dotacion',
            name='item',
            field=models.CharField(choices=[('CAMISA', 'Camisa'), ('CAMISETA', 'Camiseta'), ('JEAN', 'Jean / Pantalón'), ('BOTAS', 'Botas'), ('OTRO', 'Otro')], default='CAMISA', max_length=15),
        ),
        migrations.AlterField(
            model_name='dotacion',
            name='descripcion',
            field=models.CharField(blank=True, help_text='Talla, color u otras especificaciones.', max_length=200),
        ),
    ]
