# Generated by Django 6.1.1 on 2026-09-15 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_salariominimo_remove_dotacion_fecha_cambio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='remunerado',
            field=models.BooleanField(default=True, help_text='Si NO es remunerado, al aprobarse se descuenta automáticamente de la nómina.'),
        ),
        migrations.AlterField(
            model_name='novedadnomina',
            name='movimiento',
            field=models.CharField(choices=[('DEVENGADO', 'Remunerado (suma en nómina)'), ('DEDUCIDO', 'Deducido (resta en nómina)'), ('COMPENSABLE', 'Compensable en tiempo (sin pago)')], max_length=12),
        ),
        migrations.CreateModel(
            name='CompensacionTiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_trabajo', models.DateField(help_text='Día en que se realizó el trabajo extra (cuadrilla).')),
                ('horas', models.DecimalField(decimal_places=2, help_text='Horas a compensar.', max_digits=6)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('fecha_limite', models.DateField(help_text='Fecha máxima para tomar el tiempo (regla interna: 1 mes).')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de tomar'), ('TOMADA', 'Ya tomada')], default='PENDIENTE', max_length=10)),
                ('fecha_tomada', models.DateField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensaciones', to='gestion.empleado')),
            ],
            options={
                'verbose_name': 'Compensación de tiempo',
                'verbose_name_plural': 'Compensaciones de tiempo',
                'ordering': ['fecha_limite'],
            },
        ),
    ]
